name: E2E tests

on: push

jobs: 
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with: 
          runTests: false
      
      - name: API tests
        run: npm run api   
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
          CYPRESS_TOKEN: ${{ secrets.CYPRESS_TOKEN }}        

  ui-tests-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with: 
          runTests: false
      
      - name: UI tests - Chrome
        run: npm run percy:chrome
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
      
  ui-tests-edge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Cypress run
      uses: cypress-io/github-action@v5
      with: 
        runTests: false
    
    - name: UI tests - Edge
      run: npm run percy:edge
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
        CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
        CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
  
  ui-tests-firefox:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cypress run
      uses: cypress-io/github-action@v5
      with: 
        runTests: false

    - name: UI tests - Firefox
      run: npm run percy:firefox
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
        CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
        CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
